version: '3.1'
services: 
  
  postgres:
    image: postgres:9.6
    ports: 
      - "5432:5432"
    env_file:
      - ./local-db.env
    
    command: ["-c", "shared_buffers=256MB","-c", "max_connections=200"]
    volumes:
      - ./docker-compose-local-db.sh:/docker-entrypoint-initdb.d/docker-compose-local-db.sh               
      - ./local-db/data:/var/lib/postgresql/data

volumes: 
  local-db: {}